name: Compute nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install numpy
      - name: Run optimization
        run: python -c "from euromax_advanced import generate_pool, run_ga; import json; pool=generate_pool(50); best=run_ga(pool, gens=50); open('best_combo.json','w').write(json.dumps(best))"
      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add best_combo.json
          git commit -m "update best combo" || echo "No changes"
          git push
